### ISSUE TITLE
Error when starting up

### ISSUE THREAD

**Issue by non-Jedi** [shedatc/tw4e#1]
Decided to try running this, but I'm getting the following in `*Messages*` after
running `tw4e/popup-headers`, and the `*Task Headers*` buffer remains blank.

```
cdr: Wrong type argument: listp, "Define the format of the columns displayed in the headers buffer."
```

Any idea what's going on here?

**Comment by shedatc** [comment]
What do you get when running `task tw4e`? And what's the current value of the `tw4e/columns-definitions` variable?

**Comment by non-Jedi** [comment]
Sorry for the noise. I lost interest in interacting with tw from inside emacs. Much appreciated you trying to help.
